<?php
/**
 * Created by PhpStorm.
 * User: manus
 * Date: 16/03/16
 * Time: 13:29
 */

namespace MyNameSpace;


use GLFramework\Controller\AuthController;

class login extends AuthController
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        if(isset($_POST['login']))
        {
            if($this->processLogin())
            {
//                print_debug($this->user->json());
            }
        }

    }


}