title: maintenance
description: Permite establecer la web en modo mantenimiento.
version: 0.0.1
indev: true

app:
  index: home
  controllers: controller
  model: model
  views: view

  resources: resources

  listeners:
    beforeControllerRun: GLFramework\Modules\Maintenance\home->beforeControllerRun

  settings:
    maintenanceMessage:
      description: Añadir un mensaje de mantenimiento a todas las páginas
      type: string
      default: ~

    maintenance:
      description: Entrar en mantenimiento (Solo los admins pueden acceder al sitio)
      type: boolean
      default: false