title: maintenance
description: Permite establecer la web en modo mantenimiento.
version: 0.0.1
indev: true

app:
  index: home

  controllers: controller
  model: model
  views: views

  resources: resources

  listeners:
    - beforeControllerRun: GLFramework\Modules\Maintenance\home->beforeControllerRun