<?php
/**
 *     GLFramework, small web application framework.
 *     Copyright (C) 2016.  Manuel Muñoz Rosa
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Created by PhpStorm.
 * User: manus
 * Date: 1/03/16
 * Time: 10:33
 */

namespace GLFramework\DaMa\Manipulators;


use TijsVerkoyen\CssToInlineStyles\Exception;

class XLSManipulator extends ManipulatorCore
{

    /**
     * @var \SpreadsheetReader
     */
    var $reader;
    public function open($file, $config = array())
    {
        $this->reader = new \SpreadsheetReader_XLS($file);
    }

    public function next()
    {
        // TODO: Implement next() method.
        if($this->reader->valid())
            return array_map(array($this, 'map'), $this->reader->next());
        return false;
    }

    public function setSheet($index)
    {
        $this->reader->ChangeSheet($index);
        parent::setSheet($index); // TODO: Change the autogenerated stub
    }

    public function map($item)
    {
        return utf8_encode($item);
    }

}