<?php
/**
 * Created by PhpStorm.
 * User: manus
 * Date: 1/03/16
 * Time: 10:33
 */

namespace GLFramework\DaMa\Manipulators;


class XLSManipulator extends ManipulatorCore
{

    /**
     * @var \SpreadsheetReader
     */
    var $reader;
    public function open($file, $config = array())
    {
        $this->reader = new \SpreadsheetReader_XLS($file);
    }

    public function next()
    {
        // TODO: Implement next() method.
        if($this->reader->valid())
            return array_map(array($this, 'map'), $this->reader->next());
        return false;
    }

    public function setSheet($index)
    {
        $this->reader->ChangeSheet($index);
        parent::setSheet($index); // TODO: Change the autogenerated stub
    }

    public function map($item)
    {
        return utf8_encode($item);
    }

}