title: incidencias
description: Enviar incidencias
indev: true

app:
  controllers: controller
  views: view
  resources: assets

  routes:
    GLFramework\Modules\Incidencias\send: /incidencia/send


  settings:
    email:
      description: Mail para enviar la incidencia
      type: string
      default: soporte@gestionlan.com