<?php
/**
 * Created by PhpStorm.
 * User: manus
 * Date: 24/02/16
 * Time: 15:02
 */

namespace GLFramework\Modules\Admin;


use GLFramework\Controller\AuthController;
use GLFramework\Model\Page;
use GLFramework\Model\User;
use GLFramework\Model\UserPage;

class admin extends AuthController
{
    var $name = "Administracion Interna";
    var $admin = true;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $controller
     * @param $user User
     * @return bool
     */
    public static function isUserAllowed($controller, $user)
    {
        if($user->admin) return true;
        $page = new Page();
        $pageUser = new UserPage();
        $current = $page->get_by_controller($controller)->getModel();
        if($current->id > 0)
        {
            $pageUser = $pageUser->getByPageUser($user->id, $current->id)->getModel();
            if($pageUser->id > 0)
            {
                return $pageUser->allowed?true:false;
            }
        }
        return null;
    }

}