<?php
/**
 * Created by PhpStorm.
 * User: manus
 * Date: 06/04/17
 * Time: 12:07
 */

namespace GLFramework\Modules\Admin;


use GLFramework\Bootstrap;
use GLFramework\ConfigurationManager;
use GLFramework\Controller\AuthController;
use GLFramework\Module\Module;
use GLFramework\Module\ModuleManager;
use GLFramework\Module\ModuleScanner;

class modules extends AuthController
{

    var $admin = true;
    var $name = "Gestor de modulos";

    /**
     * @var Module[]
     */
    var $modules;
    var $module;
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $moduleScanner = new ModuleScanner();
        $this->modules = $moduleScanner->scan(".");

        $configManager = new ConfigurationManager(ConfigurationManager::getAutogeneratedFile());
        if(isset($this->params['name']))
        {
            $module = null;
            $name = urldecode($this->params['name']);
            foreach ($this->modules as $module1)
            {

                if($module1->title == $name)
                {
                    $module = $module1;
                    break;
                }
            }
            if($module != null)
            {
                if(isset($this->params['state']))
                {
                    $config = $configManager->load();
                    if($this->params['state'] == "enable")
                    {
                        $config['modules'][$module->getFolderContainer()][] = $module->getListName();
                    }
                    else if($this->params['state'] == "disable")
                    {
                        $index = array_search($module->getListName(), $config['modules'][$module->getFolderContainer()]);
                        unset($config['modules'][$module->getFolderContainer()][$index]);
                    }
                    if($configManager->save($config))
                    {
                        $this->addMessage("Se ha guardado correctamente");
                    }
                    else
                    {
                        $this->addMessage("No se ha podido guardar la configuracion", "danger");
                    }
                }
                $this->module = $module;
                $this->module->init();
                if(isset($_POST['settings']))
                {
                    $config = $configManager->load();
                    $this->setModuleConfiguration($config, $module, $_POST['settings']);
                    if($configManager->save($config))
                    {
                        $this->addMessage("Se ha guardado correctamente");
                        $this->redirection("");
                    }
                    else
                    {
                        $this->addMessage("No se ha podido guardar la configuracion", "danger");
                    }
                }
                $this->setTemplate("module.twig");
            }
            else
            {
                $this->addMessage("No se ha encontrado el módulo", "danger");
            }
        }
    }


    /**
     * @param $config
     * @param $module Module
     * @return mixed
     */
    public function getModuleConfiguration($config, $module)
    {
        $keys = $config['modules'][$module->getFolderContainer()];
        foreach ($keys as $key => $value)
        {
            if(is_array($value) && isset($value[$module->getListName()]))
            {
                return $value[$module->getListName()];
            }
        }
        return false;
    }

    /**
     * @param $config
     * @param $module Module
     * @param $settings
     * @return bool
     */
    public function setModuleConfiguration(&$config, $module, $settings)
    {
        $keys = &$config['modules'][$module->getFolderContainer()];
        foreach ($keys as $key => &$value)
        {
            if(is_array($value) && isset($value[$module->getListName()]))
            {
                $value[$module->getListName()] = $settings;
                return true;
            }
            elseif($key === $module->getListName())
            {
                print_debug($key, $module->getListName());
                die("OK");
                $value[$module->getListName()] = $settings;
                return true;

            }
        }
        return false;
    }


}