<?php
/**
 * Created by PhpStorm.
 * User: manus
 * Date: 06/04/17
 * Time: 12:07
 */

namespace GLFramework\Modules\Admin;


use GLFramework\ConfigurationManager;
use GLFramework\Controller\AuthController;
use GLFramework\Module\Module;
use GLFramework\Module\ModuleManager;
use GLFramework\Module\ModuleScanner;

class modules extends AuthController
{

    var $admin = true;
    var $name = "Gestor de modulos";

    /**
     * @var Module[]
     */
    var $modules;
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $moduleScanner = new ModuleScanner();
        $this->modules = $moduleScanner->scan(".");
        $configManager = new ConfigurationManager("autogenerated.config.yml");
        if(isset($this->params['name']))
        {
            $module = null;
            $name = urldecode($this->params['name']);
            foreach ($this->modules as $module1)
            {

                if($module1->title == $name)
                {
                    $module = $module1;
                    break;
                }
            }
            if($module != null)
            {
                if(isset($this->params['state']))
                {
                    $config = $configManager->load();
                    if($this->params['state'] == "enable")
                    {
                        $config['modules'][$module->getFolderContainer()][] = $module->getListName();
                    }
                    else if($this->params['state'] == "disable")
                    {
                        $index = array_search($module->getListName(), $config['modules'][$module->getFolderContainer()]);
                        unset($config['modules'][$module->getFolderContainer()][$index]);
                    }
                    if($configManager->save($config))
                    {
                        $this->addMessage("Se ha guardado correctamente");
                    }
                    else
                    {
                        $this->addMessage("No se ha podido guardar la configuracion", "danger");
                    }
                    $this->quit(".");
                }
            }
            else
            {
                $this->addMessage("No se ha encontrado el módulo", "danger");
            }
        }
    }


}