###
##  Installation:
##    edit config.yml, in modules section add - ga
##
#
#modules:
#    internal:
#      - ga:
#          tracker: [Google analytics tracker]
###

title: Google Analytics
description: Implementacion de evetos para Google Analytics
version: 0.0.1

app:

  views: view

  listeners:
    onMessageDisplay: GLFramework\Modules\GoogleAnalytics\GA->onMessageDisplay
    onLoginSuccess: GLFramework\Modules\GoogleAnalytics\GA->onLoginSuccess
    displayScripts: GLFramework\Modules\GoogleAnalytics\GA->addTrackerJS

  settings:
    # Name and description about the possible configuration override by the main config
    tracker:
      description: Google analytics tracker.
      type: string
      default:
    # Name and description about the possible configuration override by the main config
    auto_ga:
      description: Add Google analytics  JS script automatically.
      type: boolean
      default: false
    user_id:
      description: Track user id.
      type: boolean
      default: false