###
##  Installation:
##    edit config.yml, in modules section add - ga
##
#
#modules:
#    internal:
#      - ga:
#          tracker: [Google analytics tracker]
###

title: Google Analytics
description: Implementacion de evetos para Google Analytics
version: 0.0.1

app:

  listeners:
    onMessageDisplay: GLFramework\Modules\GoogleAnalytics\GA->onMessageDisplay
    onLoginSuccess: GLFramework\Modules\GoogleAnalytics\GA->onLoginSuccess

  settings:
    # Name and description about the possible configuration override by the main config
    tracker:
      description: Google analytics tracker.
      type: string
      default: