<?php
/**
 * Created by PhpStorm.
 * User: manus
 * Date: 13/1/16
 * Time: 17:53
 */

namespace GLFramework\Controller;


class ExceptionController extends ErrorController
{

    private $exception;
    private $exceptions = array();
    var $trace = null;

    /**
     * ExceptionController constructor.
     * @param $exception \Exception
     */
    public function __construct($exception)
    {
        parent::__construct(get_class($exception) . " " . $exception->getMessage() . " at " . $exception->getFile() . ":" . $exception->getLine());
        $this->exception = $exception;


    }

    public function expandException(\Exception $ex, &$result = array())
    {
        if($ex->getPrevious())
        {
            $this->expandException($ex, $result);
        }
        $result[] = $ex;
        return $result;
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->exceptions = $this->expandException($this->exception);
    }


}