<?php
/**
 *     GLFramework, small web application framework.
 *     Copyright (C) 2016.  Manuel Muñoz Rosa
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Created by PhpStorm.
 * User: manus
 * Date: 13/1/16
 * Time: 17:53
 */

namespace GLFramework\Controller;

/**
 * Class ExceptionController
 *
 * @package GLFramework\Controller
 */
class ExceptionController extends ErrorController
{
    var $trace = null;
    private $exception;
    private $exceptions = array();

    /**
     * ExceptionController constructor.
     * @param $exception \Exception
     */
    public function __construct($exception)
    {
        $error = get_class($exception) . ' ' . $exception->getMessage() . ' at ' . $exception->getFile() . ':';
        $error += $exception->getLine();
        parent::__construct($error);
        $this->exception = $exception;
        $this->trace = $exception->getTraceAsString();
    }

    /**
     * TODO
     *
     * @param \Exception $ex
     * @param array $result
     * @param int $limit
     * @return array
     */
    public function expandException(\Exception $ex, &$result = array(), $limit = 10)
    {
        if ($ex->getPrevious()) {
            if ($limit > 0) {
                $this->expandException($ex, $result, $limit - 1);
            }
        }
        $result[] = $ex;
        return $result;
    }

    /**
     * TODO
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->exceptions = $this->expandException($this->exception);
    }
}
