<?php




namespace GLFramework\Modules\Controller\Cron;
use Cron\CronExpression;
use GLFramework\Controller\AuthController;
use GLFramework\Model;

/**
 * Created by PhpStorm.
 * User: manus
 * Date: 25/04/16
 * Time: 10:53
 */
class cron extends AuthController
{
    var $admin = true;
    var $title = "Administrar Cron";
    var $cron;
    var $task;
    var $manager;

    public function __construct($base, $module)
    {
        parent::__construct($base, $module);
        $this->manager = new \GLFramework\Modules\Cron\Cron();
        $this->manager->generarScript();
    }


    public function run()
    {
        if(!parent::run()) return false; // TODO: Change the autogenerated stub
        $this->cron = new \Cron();
        if(isset($this->params['id']))
        {
            $this->task = new \Cron($this->params['id']);
            $this->setTemplate("edit.twig");
            if(isset($_POST['save']))
            {
                $this->task->setData($_POST);
                $cron = CronExpression::factory($this->task->cron);
                $this->addMessage("La siguiente ejecucion será: " . $cron->getNextRunDate()->format('Y-m-d H:i:s'));
                $this->task->save(true);
                if($this->params['id'] == 'add') {
                    $this->quit('/admin/cron/' . $this->task->id);
                }
            }
        }
//        $tasks = $this->manager->getTasks();
    }


}