<?php
/**
 * Created by PhpStorm.
 * User: manus
 * Date: 7/03/16
 * Time: 17:08
 */

namespace GLFramework\Modules\GroupPermissions;


use GLFramework\Controller\AuthController;

class groups_ajax extends AuthController
{
    var $admin = true;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $groups = new \Group();
        $this->setTemplate("json.twig");
        $json = $groups->search($_GET['term'])->json();
        $json = array_map(array($this, 'map'), $json);
        return array('json' => $json);
    }

    public function map($a)
    {
        return array('label' => $a['permissions']);
    }


}