<?php
/**
 * Created by PhpStorm.
 * User: manus
 * Date: 1/03/16
 * Time: 15:55
 */

namespace GLFramework\Modules\GroupPermissions;


use GLFramework\Controller\AuthController;
use GLFramework\Model\Page;
use GLFramework\Module\ModuleManager;

class groups extends AuthController
{

    var $admin = true;

    var $groups;
    var $group;

    var $controllers = array();
    var $groupPage;
    var $page;
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->groups = new \Group();
        $this->page = new Page();
        $this->groupPage = new \GroupPage();
        if(isset($_POST['save']))
        {
            $this->groups->setData($_POST);
            if($this->groups->save())
            {
                $this->addMessage("Se ha creado el grupo correctamente");
            }
            else
            {
                $this->addMessage("Se ha producido un error al guardar los datos", "danger");
            }
        }
        if(isset($this->params['id']))
        {
            if(isset($this->params['a']))
            {
                if($this->params['a'] == "remove")
                {
                    if($this->groupPage->get($this->params['page'])->getModel()->delete())
                    {
                        $this->addMessage("Se ha eliminado correctamente");
                    }
                    else
                    {
                        $this->addMessage("Se ha producido un error al eliminar", "danger");

                    }
                }
            }
            $this->group = $this->groups->get($this->params['id'])->getModel();
            foreach(ModuleManager::getInstance()->getModules() as $module)
            {
                $items = $module->getControllers();
                foreach($items as $item => $value)
                {
                    $this->controllers[] = $item;
                }
            }
            if(isset($_POST['addLink']))
            {
                $page = new Page();
                $page = $page->get(array('controller' => $_POST['controller']))->getModel();
                $page->generate($_POST['controller']);
                $page->save(true);

                $this->groupPage = $this->groupPage->get(array('id_group' => $this->params['id'], 'id_page' => $page->id))->getModel();
                $this->groupPage->id_group = $this->params['id'];
                $this->groupPage->id_page = $page->id;
                $this->groupPage->save();
            }
            $this->groupPage = $this->groupPage->get(array('id_group' => $this->params['id']))->getModels();
        }
        $this->groups = $this->groups->get_all()->getModels();




    }


}