<?php
/**
 * Created by PhpStorm.
 * User: mmuno
 * Date: 15/07/2016
 * Time: 10:29
 */

namespace GLFramework\Modules\UserPanel;


use GLFramework\Controller\AuthController;
use GLFramework\Filesystem;
use GLFramework\Image\ImageProcessing;
use GLFramework\Upload\Uploads;

class userpanel extends AuthController
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        if(isset($_POST['save']))
        {
            $this->user->setData($_POST);
            $upload = $this->getUploads()->allocate("picture");
            if($upload->isSuccess() && !$upload->isEmpty())
            {
                $name = "image_" . $this->user->id . ".png";
                $upload->setName($name);
                $image = new ImageProcessing($upload->tmpName());
                $image->open($upload->contentType());
                $image->resize_image(64, 64, false);
                $image->save($upload->getAbsolutePath());
                $this->user->profile_image = $upload->url();
            }
            $this->user->save();
            $this->addMessage("Se ha actualizado correctamente la informacion de perfil");
        }
    }


}