<?php
namespace GLFramework\Modules\API;
use GLFramework\Controller\AuthController;

/**
 * Created by PhpStorm.
 * User: manus
 * Date: 25/04/16
 * Time: 10:53
 */
class api_home extends AuthController
{
    var $admin = true;
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }


}