title: recaptcha
description: Barra para depurara aplicaciones con el framework
version: 0.0.1

app:

  listeners:
    displayScripts: GLFramework\Modules\reCAPTCHA\reCAPTCHA->displayScripts
    validateCaptha: GLFramework\Modules\reCAPTCHA\reCAPTCHA->validateCaptha
  settings:
      # Name and description about the possible configuration override by the main config
      # https://www.google.com/recaptcha/admin#list
      key:
        description: Clave del sitio
        type: string
        default:
      secret:
        description: >
          Clave secreta
          Úsala para las comunicaciones entre tu sitio y Google. Ten la precaución de no revelársela a nadie.
        type: string
        default:


