<?php
/**
 *     GLFramework, small web application framework.
 *     Copyright (C) 2016.  Manuel Muñoz Rosa
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Created by PhpStorm.
 * User: manus
 * Date: 14/03/16
 * Time: 13:08
 */

namespace GLFramework;

use Psr\Log\AbstractLogger;

/**
 * Class Log
 *
 * @package GLFramework
 */
class Log extends AbstractLogger
{
    private static $instance;

    private $debugMode = false;

    /**
     * Log constructor.
     */
    public function __construct()
    {
        self::$instance = $this;
        $config = Bootstrap::getSingleton()->getConfig();
        if (isset($config['app']['debug']) && $config['app']['debug']) {
            $this->debugMode = true;
        }
    }

    /**
     * TODO
     *
     * @return Log
     */
    public static function getInstance()
    {
        if (self::$instance === null) {
            self::$instance = new Log();
        }
        return self::$instance;
    }

    /**
     * TODO
     *
     * @param $message
     * @param array $context
     */
    public static function em($message, array $context = array())
    {
        // TODO: Change the autogenerated stub
        self::getInstance()->emergency($message, $context);
    }

    /**
     * TODO
     *
     * @param $message
     * @param array $context
     */
    public static function a($message, array $context = array())
    {
        // TODO: Change the autogenerated stub
        self::getInstance()->alert($message, $context);
    }

    /**
     * TODO
     *
     * @param $message
     * @param array $context
     */
    public static function c($message, array $context = array())
    {
        // TODO: Change the autogenerated stub
        self::getInstance()->critical($message, $context);
    }

    /**
     * TODO
     *
     * @param $message
     * @param array $context
     */
    public static function e($message, array $context = array())
    {
        // TODO: Change the autogenerated stub
        self::getInstance()->error($message, $context);
    }

    /**
     * TODO
     *
     * @param $message
     * @param array $context
     */
    public static function w($message, array $context = array())
    {
        // TODO: Change the autogenerated stub
        self::getInstance()->warning($message, $context);
    }

    /**
     * TODO
     *
     * @param $message
     * @param array $context
     */
    public static function n($message, array $context = array())
    {
        // TODO: Change the autogenerated stub
        self::getInstance()->notice($message, $context);
    }

    /**
     * TODO
     *
     * @param $message
     * @param array $context
     */
    public static function i($message, array $context = array())
    {
        // TODO: Change the autogenerated stub
        self::getInstance()->info($message, $context);
    }

    /**
     * TODO
     *
     * @param $message
     * @param array $context
     */
    public static function d($message, array $context = array())
    {
        // TODO: Change the autogenerated stub
        self::getInstance()->debug($message, $context);
    }

    /**
     * Logs with an arbitrary level.
     *
     * @param mixed $level
     * @param string $message
     * @param array $context
     * @return null
     */
    public function log($level, $message, array $context = array())
    {
        if($this->debugMode)
        {
            error_log("[$level] " . (is_string($message)?$message:implode(", ", $message)));
        }
        // TODO: Implement log() method.
        if (!in_array('events', $context)) {
            Events::dispatch('onLog', array($message, $level));
        } else {
            if ($this->debugMode) {
                echo '<pre>';
                echo($level . ' ' . $message . "\n");
                debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
                echo '</pre>';
                die();
            }
        }
    }
}
