title: debugbar
description: Barra para depurara aplicaciones con el framework
version: 0.0.1

app:
  index: home

  controllers: controller
  model: model
  views: views

  resources: resources

  listeners:
    onCoreStartUp: GLFramework\Modules\Debugbar\Debugbar->onCoreStartUp
    onCoreRunFinish: GLFramework\Modules\Debugbar\Debugbar->onCoreRunFinish
    beforeControllerRun: GLFramework\Modules\Debugbar\Debugbar->beforeControllerRun
    afterControllerRun: GLFramework\Modules\Debugbar\Debugbar->afterControllerRun
    onLog: GLFramework\Modules\Debugbar\Debugbar->onLog
    onMessageDisplay: GLFramework\Modules\Debugbar\Debugbar->onMessageDisplay
    displayScripts: GLFramework\Modules\Debugbar\Debugbar->displayScripts
    displayStyle: GLFramework\Modules\Debugbar\Debugbar->displayStyle
    onPDOCreated: GLFramework\Modules\Debugbar\Debugbar->onPDOCreated
    onViewCreated: GLFramework\Modules\Debugbar\Debugbar->onViewCreated