title: debugbar
description: Barra para depurar aplicaciones con el framework
version: 0.0.1

app:
  controllers: controller
  resources:

  listeners:
    onCoreStartUp: GLFramework\Modules\Debugbar\Debugbar->onCoreStartUp
    onCoreRunFinish: GLFramework\Modules\Debugbar\Debugbar->onCoreRunFinish
    beforeControllerRun: GLFramework\Modules\Debugbar\Debugbar->beforeControllerRun
    afterControllerRun: GLFramework\Modules\Debugbar\Debugbar->afterControllerRun
    beforeViewDisplay: GLFramework\Modules\Debugbar\Debugbar->beforeViewDisplay
    afterViewDisplay: GLFramework\Modules\Debugbar\Debugbar->afterViewDisplay
    onLog: GLFramework\Modules\Debugbar\Debugbar->onLog

    onMessageDisplay: GLFramework\Modules\Debugbar\Debugbar->onMessageDisplay
    displayScripts: GLFramework\Modules\Debugbar\Debugbar->displayScripts
    displayStyle: GLFramework\Modules\Debugbar\Debugbar->displayStyle
    onPDOCreated: GLFramework\Modules\Debugbar\Debugbar->onPDOCreated
    onViewCreated: GLFramework\Modules\Debugbar\Debugbar->onViewCreated
    beforeResponseSend: GLFramework\Modules\Debugbar\Debugbar->beforeResponseSend
    afterResponseSend: GLFramework\Modules\Debugbar\Debugbar->afterResponseSend
    onMailTransport: GLFramework\Modules\Debugbar\Debugbar->onMailTransport
    onException: GLFramework\Modules\Debugbar\Debugbar->exceptionHandler

  routes:
      - GLFramework\Modules\Debugbar\handler: /debugbar/handler
  settings:
      # Name and description about the possible configuration override by the main config
      filesystem:
        description: true o false para que DebugBar almacene todas la peticiones para que se pueda depurar en un futuro.
        type: boolean
        default: false
      headerSize:
        description: Tamaño maximo de las cabezeras
        type: number
        default: 4096
