title: group_permissions
description: Permite agrupar paginas y dar acceso a los usuarios.
version: 0.0.0

app:
  index: home
  controllers: controller
  model: model
  views: views

  routes:
      - GLFramework\Modules\GroupPermissions\groups: /admin/groups/[i:id]?/[a:a]?/[i:page]?
      - GLFramework\Modules\GroupPermissions\groups_ajax: /admin/ajax/groups

  listeners:
    beforeControllerRun: GLFrameworkModules\EventReceiver->beforeControllerRun
    isUserAllowed: GLFrameworkModules\EventReceiver->isUserAllowed
    getAdminControllers: GLFrameworkModules\EventReceiver->getAdminControllers

  settings:
    # Name and description about the possible configuration override by the main config
    allowDefault:
      description: >
        Especifica si cuando no se a definido el acceso a un grupo se permite el acesso.
        Valores: 1 para indicar que se permite el acceso, 0 para que tome la configuracion por defecto.
      type: boolean
      default: false