title: api
description: Implementa las funciones para authorizar a las peticiones API
version: 0.0.1

app:
  index: home

  controllers: controller
  model: model
  views: views
  routes:
      GLFramework\Modules\Controller\API\api: /api/manager/[*:id]?

  listeners:
    afterControllerConstruct: GLFramework\Modules\API\API->afterControllerConstruct
    getAdminControllers: GLFramework\Modules\API\API->getAdminControllers

