title: api
description: Implementa las funciones para authorizar a las peticiones API
version: 0.0.1

app:
  index: home

  controllers: controllers
  model: model
  views: views
  routes:
      GLFramework\Modules\API\api_home: /api/manager

  listeners:
    afterControllerConstruct: GLFramework\Modules\API\API->afterControllerConstruct
