<?php




namespace GLFramework\Modules\Controller\API;
use GLFramework\Controller\AuthController;
use GLFramework\Model;

/**
 * Created by PhpStorm.
 * User: manus
 * Date: 25/04/16
 * Time: 10:53
 */
class api extends AuthController
{
    var $admin = true;
    var $title = "Administrar acceso API";
    
    var $apiAuthorization;
    var $users;
    public function run()
    {
        if(!parent::run()) return false; // TODO: Change the autogenerated stub
        $this->apiAuthorization = new \APIAuthorization();

        if(isset($_GET['remove']))
        {
            $this->apiAuthorization = new \APIAuthorization($_GET['remove']);
            if($this->apiAuthorization->delete())
            {
                $this->addMessage("Se ha eliminado correctamente");
            }
            else{
                $this->addMessage("No se ha podido eliminar esta entrada", "danger");

            }
        }
        if(isset($this->params['id']))
        {
            $this->apiAuthorization = new \APIAuthorization($this->params['id']);
            if(isset($_POST['save']))
            {
                if(!$this->apiAuthorization->id) $this->apiAuthorization->id = null;
                $_POST['date'] = now();
                $this->apiAuthorization->setData($_POST);
                if($this->apiAuthorization->save(true))
                {
                    $this->addMessage("Se han guardado los cambios correctamente!");
                }
                else{
                    $this->addMessage("No se ha podido guardar estos cambios", "danger");

                }
            }
            $this->users = Model::newInstance("User");
            if($this->apiAuthorization->id || $this->params['id'] == "add")
            {
               $this->setTemplate("api_edit.twig");
            }
            else
            {
                $this->addMessage("No se encuentra ese registro", "danger");
            }
        }
    }


}